version: '3.7'
services:
  db:
    image: postgres:13
    volumes:
      - ./movies_database.dump:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    restart: always

  elk:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200

  postgres_to_es:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
      - elk
    restart: always
